set ROOT=%~dp0
set ROOT=%ROOT:\=\\%

set WXW_ROOT=%ROOT%\libraries\wxWidgets
set WXW_LIBS=%WXW_ROOT%\lib\vc_x64_dll
set CMAKE_PREFIX_PATH=%WXW_ROOT%;%CMAKE_PREFIX_PATH%
set PATH=%WXW_LIBS%;%PATH%

set ZLIB_ROOT=%ROOT%\libraries\zlib
set ZLIB_LIBS=%ZLIB_ROOT%\lib
set CMAKE_PREFIX_PATH=%ZLIB_ROOT%;%CMAKE_PREFIX_PATH%
set PATH=%ZLIB_LIBS%;%PATH%